language: php
php:
- 7.1
- 7.2
before_script:
- sudo apt-get install libxml2-utils
- composer self-update
- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGE_LOGIN}\",\"password\":\"${MAGE_PWD}\"}}}" > auth.json
- phpenv config-rm xdebug.ini
- composer install --no-interaction --prefer-dist
- php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
- php vendor/bin/phpcs --config-set show_warnings 0
script:
- php vendor/bin/grumphp run
env:
  global:
    secure: H5bXPoCVknXP0CK8rOugITymoICT9qz9raZZrQ46moBstw7535+m2+KzjdN6f/r/MXL47gzWPIZ5j6Yeusvue7Ccr7zUvqsusNv3uziMDZt3y5tfZ5t3eW+w9R38Ttn3JLjXjzVDIRq5EIRHTZAFPBwNIWEC86vnm3LxrFphhAWk6MkSmxU4kuVvfWyaw+YRsluU+PARYVgDKkqSjQ7Swan9jCPspnu0PknmIYMmLP8GsX5jCUCkgbU+Cvg7pR4RDrWnKlV5YSWxm7C7lZbW5BDEgQ51S9tJuCxIMk+T5v+BDQ7bDGBUf4CJnaROWXxH+953DuMgwdNU1NyHPPFct4sFJru2nTW1RwdKh9WXyrdt6vW//j6JohNrXxf+YkXgynL92qB+j9QLuckv4EEt+Xc7HxxpvKltXVnkJiPXtM5MF4QCAYRhKmDQ8LzTnv6CtdzPQR781gN9s0r3Tt06E7eY60KNFSfxzbS0GjvpzRFfeTy13LwNwUWVi20sxtxKlf7xZft9KB30779p/+I6IgdtCFtYn4uFMQt0wfokzC0aBKtd2txbwat/BRzXuzj/FL0jwdVgTxf1xAXtl2nCYITVbSRT3OsfmWRTIVEGUInNexY0++JYYABH19SxRBVFme6cCPnKsJJPYJVtdRq4pH0rDF0TT1IWUp9zo/54ovc=
